#!/bin/bash

# Enable the proxy extension in notebook and lab
jupyter serverextension enable --py jupyter_server_proxy
jupyter labextension install @jupyterlab/server-proxy
jupyter lab build

code-server --install-extension ms-python.python 
code-server --install-extension redhat.vscode-yaml
# Install the VS code proxy
pip install -e.

mamba create -n env_otb otb -c conda-forge -c terradue
mamba create -n env_gdal gdal -c conda-forge -c terradue
# create -n env_snap snap -c conda-forge -c terradue